package com.bohai.adviser.entity.dztg;

import java.util.Date;

public class SysPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZTG.SYS_PERMISSIONS.ID
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZTG.SYS_PERMISSIONS.PERMISSION
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZTG.SYS_PERMISSIONS.PERMISSION_LEVEL
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    private String permissionLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZTG.SYS_PERMISSIONS.PARENT_PERMISSION_ID
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    private String parentPermissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZTG.SYS_PERMISSIONS.DESCRIPTION
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZTG.SYS_PERMISSIONS.AVAILABLE
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    private String available;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZTG.SYS_PERMISSIONS.URL
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZTG.SYS_PERMISSIONS.SORT
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    private Short sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZTG.SYS_PERMISSIONS.CREATE_TIME
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZTG.SYS_PERMISSIONS.UPDATE_TIME
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZTG.SYS_PERMISSIONS.ID
     *
     * @return the value of DZTG.SYS_PERMISSIONS.ID
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZTG.SYS_PERMISSIONS.ID
     *
     * @param id the value for DZTG.SYS_PERMISSIONS.ID
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZTG.SYS_PERMISSIONS.PERMISSION
     *
     * @return the value of DZTG.SYS_PERMISSIONS.PERMISSION
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZTG.SYS_PERMISSIONS.PERMISSION
     *
     * @param permission the value for DZTG.SYS_PERMISSIONS.PERMISSION
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZTG.SYS_PERMISSIONS.PERMISSION_LEVEL
     *
     * @return the value of DZTG.SYS_PERMISSIONS.PERMISSION_LEVEL
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    public String getPermissionLevel() {
        return permissionLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZTG.SYS_PERMISSIONS.PERMISSION_LEVEL
     *
     * @param permissionLevel the value for DZTG.SYS_PERMISSIONS.PERMISSION_LEVEL
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    public void setPermissionLevel(String permissionLevel) {
        this.permissionLevel = permissionLevel == null ? null : permissionLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZTG.SYS_PERMISSIONS.PARENT_PERMISSION_ID
     *
     * @return the value of DZTG.SYS_PERMISSIONS.PARENT_PERMISSION_ID
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    public String getParentPermissionId() {
        return parentPermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZTG.SYS_PERMISSIONS.PARENT_PERMISSION_ID
     *
     * @param parentPermissionId the value for DZTG.SYS_PERMISSIONS.PARENT_PERMISSION_ID
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    public void setParentPermissionId(String parentPermissionId) {
        this.parentPermissionId = parentPermissionId == null ? null : parentPermissionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZTG.SYS_PERMISSIONS.DESCRIPTION
     *
     * @return the value of DZTG.SYS_PERMISSIONS.DESCRIPTION
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZTG.SYS_PERMISSIONS.DESCRIPTION
     *
     * @param description the value for DZTG.SYS_PERMISSIONS.DESCRIPTION
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZTG.SYS_PERMISSIONS.AVAILABLE
     *
     * @return the value of DZTG.SYS_PERMISSIONS.AVAILABLE
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    public String getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZTG.SYS_PERMISSIONS.AVAILABLE
     *
     * @param available the value for DZTG.SYS_PERMISSIONS.AVAILABLE
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    public void setAvailable(String available) {
        this.available = available == null ? null : available.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZTG.SYS_PERMISSIONS.URL
     *
     * @return the value of DZTG.SYS_PERMISSIONS.URL
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZTG.SYS_PERMISSIONS.URL
     *
     * @param url the value for DZTG.SYS_PERMISSIONS.URL
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZTG.SYS_PERMISSIONS.SORT
     *
     * @return the value of DZTG.SYS_PERMISSIONS.SORT
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    public Short getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZTG.SYS_PERMISSIONS.SORT
     *
     * @param sort the value for DZTG.SYS_PERMISSIONS.SORT
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    public void setSort(Short sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZTG.SYS_PERMISSIONS.CREATE_TIME
     *
     * @return the value of DZTG.SYS_PERMISSIONS.CREATE_TIME
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZTG.SYS_PERMISSIONS.CREATE_TIME
     *
     * @param createTime the value for DZTG.SYS_PERMISSIONS.CREATE_TIME
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZTG.SYS_PERMISSIONS.UPDATE_TIME
     *
     * @return the value of DZTG.SYS_PERMISSIONS.UPDATE_TIME
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZTG.SYS_PERMISSIONS.UPDATE_TIME
     *
     * @param updateTime the value for DZTG.SYS_PERMISSIONS.UPDATE_TIME
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}