package com.bohai.adviser.entity.dztg;

import java.util.Date;

public class SysUsersPermissions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZTG.SYS_USERS_PERMISSIONS.USER_NAME
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZTG.SYS_USERS_PERMISSIONS.PERMISSION
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZTG.SYS_USERS_PERMISSIONS.CREATE_TIME
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DZTG.SYS_USERS_PERMISSIONS.UPDATE_TIME
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZTG.SYS_USERS_PERMISSIONS.USER_NAME
     *
     * @return the value of DZTG.SYS_USERS_PERMISSIONS.USER_NAME
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZTG.SYS_USERS_PERMISSIONS.USER_NAME
     *
     * @param userName the value for DZTG.SYS_USERS_PERMISSIONS.USER_NAME
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZTG.SYS_USERS_PERMISSIONS.PERMISSION
     *
     * @return the value of DZTG.SYS_USERS_PERMISSIONS.PERMISSION
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZTG.SYS_USERS_PERMISSIONS.PERMISSION
     *
     * @param permission the value for DZTG.SYS_USERS_PERMISSIONS.PERMISSION
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZTG.SYS_USERS_PERMISSIONS.CREATE_TIME
     *
     * @return the value of DZTG.SYS_USERS_PERMISSIONS.CREATE_TIME
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZTG.SYS_USERS_PERMISSIONS.CREATE_TIME
     *
     * @param createTime the value for DZTG.SYS_USERS_PERMISSIONS.CREATE_TIME
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DZTG.SYS_USERS_PERMISSIONS.UPDATE_TIME
     *
     * @return the value of DZTG.SYS_USERS_PERMISSIONS.UPDATE_TIME
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DZTG.SYS_USERS_PERMISSIONS.UPDATE_TIME
     *
     * @param updateTime the value for DZTG.SYS_USERS_PERMISSIONS.UPDATE_TIME
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}