package com.bohai.adviser.persistence.dztg;

import java.util.List;
import java.util.Map;

import com.bohai.adviser.entity.dztg.SysPermission;

public interface SysPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZTG.SYS_PERMISSIONS
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZTG.SYS_PERMISSIONS
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    int insert(SysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZTG.SYS_PERMISSIONS
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    int insertSelective(SysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZTG.SYS_PERMISSIONS
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    SysPermission selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZTG.SYS_PERMISSIONS
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    int updateByPrimaryKeySelective(SysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZTG.SYS_PERMISSIONS
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    int updateByPrimaryKey(SysPermission record);
    
    List<SysPermission> queryPermissionsByParentPermissionId(Map<String, Object> map);
}