package com.bohai.adviser.persistence.dztg;

import com.bohai.adviser.entity.dztg.SysUser;

public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZTG.SYS_USERS
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZTG.SYS_USERS
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZTG.SYS_USERS
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    int insertSelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZTG.SYS_USERS
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    SysUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZTG.SYS_USERS
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    int updateByPrimaryKeySelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DZTG.SYS_USERS
     *
     * @mbggenerated Wed Aug 09 10:51:07 CST 2017
     */
    int updateByPrimaryKey(SysUser record);
    
    /**
     * 根据用户名查询用户信息
     * @param username
     * @return
     */
    SysUser queryUserByUsername(String username);
}