package com.bohai.adviser.persistence.sjzx;

import java.util.List;

import com.bohai.adviser.entity.sjzx.CrmCustomer;
import com.bohai.adviser.vo.InvestorProfitParamVO;
import com.bohai.adviser.vo.InvestorProfitResultVO;

public interface CrmCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_CUSTOMER
     *
     * @mbggenerated Wed Aug 09 16:43:17 CST 2017
     */
    int deleteByPrimaryKey(String investorNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_CUSTOMER
     *
     * @mbggenerated Wed Aug 09 16:43:17 CST 2017
     */
    int insert(CrmCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_CUSTOMER
     *
     * @mbggenerated Wed Aug 09 16:43:17 CST 2017
     */
    int insertSelective(CrmCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_CUSTOMER
     *
     * @mbggenerated Wed Aug 09 16:43:17 CST 2017
     */
    CrmCustomer selectByPrimaryKey(String investorNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_CUSTOMER
     *
     * @mbggenerated Wed Aug 09 16:43:17 CST 2017
     */
    int updateByPrimaryKeySelective(CrmCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_CUSTOMER
     *
     * @mbggenerated Wed Aug 09 16:43:17 CST 2017
     */
    int updateByPrimaryKey(CrmCustomer record);
    
    List<InvestorProfitResultVO> queryInvestorProfitByMarketer(InvestorProfitParamVO paramVO);
}