package com.bohai.adviser.persistence.sjzx;

import com.bohai.adviser.entity.sjzx.CrmMarketer;

public interface CrmMarketerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_MARKETER
     *
     * @mbggenerated Wed Aug 09 10:41:18 CST 2017
     */
    int deleteByPrimaryKey(String marketerNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_MARKETER
     *
     * @mbggenerated Wed Aug 09 10:41:18 CST 2017
     */
    int insert(CrmMarketer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_MARKETER
     *
     * @mbggenerated Wed Aug 09 10:41:18 CST 2017
     */
    int insertSelective(CrmMarketer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_MARKETER
     *
     * @mbggenerated Wed Aug 09 10:41:18 CST 2017
     */
    CrmMarketer selectByPrimaryKey(String marketerNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_MARKETER
     *
     * @mbggenerated Wed Aug 09 10:41:18 CST 2017
     */
    int updateByPrimaryKeySelective(CrmMarketer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_MARKETER
     *
     * @mbggenerated Wed Aug 09 10:41:18 CST 2017
     */
    int updateByPrimaryKey(CrmMarketer record);
}