package com.bohai.adviser.persistence.sjzx;

import java.util.List;

import org.apache.ibatis.annotations.Select;

import com.bohai.adviser.entity.sjzx.CrmMediator;
import com.bohai.adviser.vo.CrmMediatorAndCustomer;
import com.bohai.adviser.vo.MediatorProfitParamVO;
import com.bohai.adviser.vo.MediatorProfitResultVO;
import com.bohai.adviser.vo.QueryCrmMediatorParamVO;

public interface CrmMediatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_MEDIATOR
     *
     * @mbggenerated Wed Aug 09 16:43:17 CST 2017
     */
    int deleteByPrimaryKey(String mediatorNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_MEDIATOR
     *
     * @mbggenerated Wed Aug 09 16:43:17 CST 2017
     */
    int insert(CrmMediator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_MEDIATOR
     *
     * @mbggenerated Wed Aug 09 16:43:17 CST 2017
     */
    int insertSelective(CrmMediator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_MEDIATOR
     *
     * @mbggenerated Wed Aug 09 16:43:17 CST 2017
     */
    CrmMediator selectByPrimaryKey(String mediatorNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_MEDIATOR
     *
     * @mbggenerated Wed Aug 09 16:43:17 CST 2017
     */
    int updateByPrimaryKeySelective(CrmMediator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_MEDIATOR
     *
     * @mbggenerated Wed Aug 09 16:43:17 CST 2017
     */
    int updateByPrimaryKey(CrmMediator record);
    
    List<MediatorProfitResultVO> queryMediatorProfitByMarketer(MediatorProfitParamVO paramVO);
    
    /**
     * 根据条件查询居间人信息
     * @param paramVO
     * @return
     */
    List<CrmMediator> selectByCondition(QueryCrmMediatorParamVO paramVO);
    
    List<CrmMediatorAndCustomer> selectMediatorCustomerRelation(QueryCrmMediatorParamVO paramVO);
    
    @Select("select count(1) from T_CRM_MEDIATOR where belong_type = '1' and belong_to = #{0}")
    Long countByMarketerNo(String marketerNo);
}