package com.bohai.adviser.persistence.sjzx;

import java.util.List;

import com.bohai.adviser.entity.sjzx.CrmMarketer;
import com.bohai.adviser.vo.MarketerProfitParamVO;
import com.bohai.adviser.vo.MarketerProfitResultVO;

public interface CrmMarketerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_MARKETER
     *
     * @mbggenerated Wed Aug 09 10:41:18 CST 2017
     */
    int deleteByPrimaryKey(String marketerNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_MARKETER
     *
     * @mbggenerated Wed Aug 09 10:41:18 CST 2017
     */
    int insert(CrmMarketer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_MARKETER
     *
     * @mbggenerated Wed Aug 09 10:41:18 CST 2017
     */
    int insertSelective(CrmMarketer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_MARKETER
     *
     * @mbggenerated Wed Aug 09 10:41:18 CST 2017
     */
    CrmMarketer selectByPrimaryKey(String marketerNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_MARKETER
     *
     * @mbggenerated Wed Aug 09 10:41:18 CST 2017
     */
    int updateByPrimaryKeySelective(CrmMarketer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_MARKETER
     *
     * @mbggenerated Wed Aug 09 10:41:18 CST 2017
     */
    int updateByPrimaryKey(CrmMarketer record);
    
    List<MarketerProfitResultVO> queryMarketerSelfProfit(MarketerProfitParamVO paramVO);
}