package com.bohai.adviser.persistence.sjzx;

import java.util.List;

import com.bohai.adviser.entity.sjzx.CrmMediator;
import com.bohai.adviser.vo.MediatorProfitParamVO;
import com.bohai.adviser.vo.MediatorProfitResultVO;

public interface CrmMediatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_MEDIATOR
     *
     * @mbggenerated Wed Aug 09 16:43:17 CST 2017
     */
    int deleteByPrimaryKey(String mediatorNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_MEDIATOR
     *
     * @mbggenerated Wed Aug 09 16:43:17 CST 2017
     */
    int insert(CrmMediator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_MEDIATOR
     *
     * @mbggenerated Wed Aug 09 16:43:17 CST 2017
     */
    int insertSelective(CrmMediator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_MEDIATOR
     *
     * @mbggenerated Wed Aug 09 16:43:17 CST 2017
     */
    CrmMediator selectByPrimaryKey(String mediatorNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_MEDIATOR
     *
     * @mbggenerated Wed Aug 09 16:43:17 CST 2017
     */
    int updateByPrimaryKeySelective(CrmMediator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_MEDIATOR
     *
     * @mbggenerated Wed Aug 09 16:43:17 CST 2017
     */
    int updateByPrimaryKey(CrmMediator record);
    
    List<MediatorProfitResultVO> queryMediatorProfitByMarketer(MediatorProfitParamVO paramVO);
}