package com.bohai.adviser.persistence.sjzx;

import java.util.List;

import com.bohai.adviser.entity.sjzx.CrmMarketer;
import com.bohai.adviser.vo.CrmMarketerAndCustomer;
import com.bohai.adviser.vo.CrmMarketerAndMediator;
import com.bohai.adviser.vo.MarketerProfitParamVO;
import com.bohai.adviser.vo.MarketerProfitResultVO;
import com.bohai.adviser.vo.QueryCrmMarketerParamVO;

public interface CrmMarketerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_MARKETER
     *
     * @mbggenerated Wed Aug 09 10:41:18 CST 2017
     */
    int deleteByPrimaryKey(String marketerNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_MARKETER
     *
     * @mbggenerated Wed Aug 09 10:41:18 CST 2017
     */
    int insert(CrmMarketer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_MARKETER
     *
     * @mbggenerated Wed Aug 09 10:41:18 CST 2017
     */
    int insertSelective(CrmMarketer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_MARKETER
     *
     * @mbggenerated Wed Aug 09 10:41:18 CST 2017
     */
    CrmMarketer selectByPrimaryKey(String marketerNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_MARKETER
     *
     * @mbggenerated Wed Aug 09 10:41:18 CST 2017
     */
    int updateByPrimaryKeySelective(CrmMarketer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_CRM_MARKETER
     *
     * @mbggenerated Wed Aug 09 10:41:18 CST 2017
     */
    int updateByPrimaryKey(CrmMarketer record);
    
    List<MarketerProfitResultVO> queryMarketerSelfProfit(MarketerProfitParamVO paramVO);
    
    List<CrmMarketer> selectByCondition(QueryCrmMarketerParamVO paramVO);

    List<CrmMarketerAndMediator> selectMaketerRelation(QueryCrmMarketerParamVO paramVO);
    
    List<CrmMarketerAndCustomer> selectMaketerCustomerRelation(QueryCrmMarketerParamVO paramVO);
    
    /**
     * 查询最近一个月营销人员提成比例
     * @param marketerNo
     * @return
     */
    String getMarketerRate(String marketerNo);
}