package com.bohai.adviser.persistence.sjzx;

import com.bohai.adviser.entity.sjzx.RebateList;

public interface RebateListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_REBATE_LIST
     *
     * @mbggenerated Thu Aug 17 16:48:04 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_REBATE_LIST
     *
     * @mbggenerated Thu Aug 17 16:48:04 CST 2017
     */
    int insert(RebateList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_REBATE_LIST
     *
     * @mbggenerated Thu Aug 17 16:48:04 CST 2017
     */
    int insertSelective(RebateList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_REBATE_LIST
     *
     * @mbggenerated Thu Aug 17 16:48:04 CST 2017
     */
    RebateList selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_REBATE_LIST
     *
     * @mbggenerated Thu Aug 17 16:48:04 CST 2017
     */
    int updateByPrimaryKeySelective(RebateList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_REBATE_LIST
     *
     * @mbggenerated Thu Aug 17 16:48:04 CST 2017
     */
    int updateByPrimaryKey(RebateList record);
    
    RebateList selectOneByMediatorNo(String MediatorNo);
}