package com.bohai.adviser.persistence.sjzx;

import com.bohai.adviser.entity.sjzx.SpecialReturn;

public interface SpecialReturnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_SPECIAL_RETURN
     *
     * @mbggenerated Thu Aug 17 16:48:04 CST 2017
     */
    int deleteByPrimaryKey(String investorNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_SPECIAL_RETURN
     *
     * @mbggenerated Thu Aug 17 16:48:04 CST 2017
     */
    int insert(SpecialReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_SPECIAL_RETURN
     *
     * @mbggenerated Thu Aug 17 16:48:04 CST 2017
     */
    int insertSelective(SpecialReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_SPECIAL_RETURN
     *
     * @mbggenerated Thu Aug 17 16:48:04 CST 2017
     */
    SpecialReturn selectByPrimaryKey(String investorNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_SPECIAL_RETURN
     *
     * @mbggenerated Thu Aug 17 16:48:04 CST 2017
     */
    int updateByPrimaryKeySelective(SpecialReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SJZX.T_SPECIAL_RETURN
     *
     * @mbggenerated Thu Aug 17 16:48:04 CST 2017
     */
    int updateByPrimaryKey(SpecialReturn record);
    
    SpecialReturn selectOneByMediatorNo(String mediatorNo);
}